<?php
class isFormatHelper
{

    public $BranchId;
    public $DisplayBranchId;
    public $CustName;
    public $CustPass;
    public $CustGender = "";
    public $CustPOB = "";
    public $CustDOB = "";
    public $CustIdType = "";
    public $CustIdNumber = "";
    public $CustCompany = "";
    public $CustBusName = "";
    public $BusId = "";
    public $CustJobTitle = "";
    public $CustResAdd1 = "";
    public $CustResAdd2 = "";
    public $CustResCity = "";
    public $CustResZC = "";
    public $CustResPhone = "";
    public $CustOfficeAdd1 = "";
    public $CustOfficeAdd2 = "";
    public $CustOfficeCity = "";
    public $CustOfficeZC = "";
    public $CustOfficePhone = "";
    public $CustBillingAdd = "";
    public $CustHP = "";
    public $CustFax = "";
    public $CustEmail = "";
    public $CustTechCP = "";
    public $CustTechCPPosition = "";
    public $CustTechCPPhone = "";
    public $CustTechCPEmail = "";
    public $CustBillCP = "";
    public $CustBillCPPosition = "";
    public $CustBillCPPhone = "";
    public $CustBillCPEmail = "";
    public $CustBillMethodLetter = "";
    public $CustBillMethodEmail = "";
    public $CustBalance = "";
    public $CustRegDate = "";
    public $CustNotes = "";
    public $EmpApproval = "";
    public $CustFlag = "";
    public $TaxType = "";
    public $SalesId = "";
    public $Surveyor = "";
    public $InsertEmpId = "";
    public $InsertDateTime = "";
    public function __construct()
    {
        $this->BranchId = "";
        $this->DisplayBranchId = "";
        $this->CustName = "";
        $this->CustPass = "";
        $this->CustGender = "";
        $this->CustPOB = "";
        $this->CustDOB = "";
        $this->CustIdType = "";
        $this->CustIdNumber = "";
        $this->CustCompany = "";
        $this->CustBusName = "";
        $this->BusId = "";
        $this->CustJobTitle = "";
        $this->CustResAdd1 = "";
        $this->CustResAdd2 = "";
        $this->CustResCity = "";
        $this->CustResZC = "";
        $this->CustResPhone = "";
        $this->CustOfficeAdd1 = "";
        $this->CustOfficeAdd2 = "";
        $this->CustOfficeCity = "";
        $this->CustOfficeZC = "";
        $this->CustOfficePhone = "";
        $this->CustBillingAdd = "";
        $this->CustHP = "";
        $this->CustFax = "";
        $this->CustEmail = "";
        $this->CustTechCP = "";
        $this->CustTechCPPosition = "";
        $this->CustTechCPPhone = "";
        $this->CustTechCPEmail = "";
        $this->CustBillCP = "";
        $this->CustBillCPPosition = "";
        $this->CustBillCPPhone = "";
        $this->CustBillCPEmail = "";
        $this->CustBillMethodLetter = "";
        $this->CustBillMethodEmail = "";
        $this->CustBalance = "";
        $this->CustRegDate = "";
        $this->CustNotes = "";
        $this->EmpApproval = "";
        $this->CustFlag = "";
        $this->TaxType = "";
        $this->SalesId = "";
        $this->Surveyor = "";
        $this->InsertEmpId = "";
        $this->InsertDateTime = "";
    }
}
